var commonUrl=location.href.split('page')[0]//.../src
//导航信息
var navInfo=[
{name:'首页'},
{name:'中国',type:'city',city:'China',countryFlag:commonUrl+'image/flag-china.png'},
{name:'巴黎',type:'city',city:'Paris',countryFlag:commonUrl+'image/flag-France.png'},
{name:'纽约',type:'city',city:'newYork',countryFlag:commonUrl+'image/flag-American.png'},
{name:'伦敦',type:'city',city:'London',countryFlag:commonUrl+'image/flag-Britain.png'},
{name:'米兰',type:'city',city:'Milan',countryFlag:commonUrl+'image/flag-Italy.png'},
{name:'台湾',type:'city',city:'taiwan',countryFlag:commonUrl+'image/flag-china.png'},
{name:'北欧',type:'city',city:'NorthernEurope',countryFlag:commonUrl+'image/flag-Fashion.png'},
{name:'时尚合作',type:'city',city:'shishanghezuo',countryFlag:commonUrl+'image/flag-Fashion.png'},
];
// 设计师信息
var designerInfo=[{
			name:'KING',
			id:'king',
			city:'newYork',				
			discribCity:'NEW YORK',
			discribTit:'ALEXANDER KING',
			discribBrand:['ALEXANDER KING CHEN','设计师陈科維ALEX的同名品牌'],
			meContent:['亚洲设计师，设计前卫、大胆，不按牌理出牌，独树一格，媒体新宠儿，也是国内手屈一指的黄金单身汉之一。经常受邀至纽约，上海举办服装秀，2017世界皮草协会，唯一赞助品牌盛名也是众多女星拥护者，范冰冰、蔡依林、萧亚轩、田馥甄、张韶涵、Ella等…','2009年在纽约自创同名品牌之后，因为家庭因素将其带回亚洲。主要销售区域为台湾。'],
			desiginBigimg:commonUrl+'image/king-big.png',
			desiginSmallimg:commonUrl+'image/king-small.png',		
			background:commonUrl+'image/king-bg.png',	
			headImg:commonUrl+'image/king-head.png',			
			countryName:'美国',	
			countryFlag:commonUrl+'image/flag-American.png',
			html:commonUrl+'page/king.html'
		},{
			name:'杨峻杰',	
			id:'yangjunjie',
			city:'newYork',			
			discribCity:'NEW YORK',
			discribTit:'杨峻杰',
			discribBrand:['清华大学美术学院服装设计系','安特卫普皇家艺术学院'],
			meContent:[' 曾在比利时设计师Raf Simons工作室以男装设计师的职务实习，目前在比利时品牌Walter Van Beirandonck担任印花设计兼男装设计助理职务。','于2017年在比利时安特卫普的男装品牌，致力于塑造东方审美情趣为主导内核，同西方后现代主义结合的千禧一代的年轻时装。年轻，无惧（young,bold,daring,smart)是品牌想要传递的形象。主要销售区域为中国。'],
			desiginBigimg:commonUrl+'image/yangjunjie-big.png',
			desiginSmallimg:commonUrl+'image/yangjunjie-small.png',		
			background:commonUrl+'image/yangjunjie-bg.png',	
			headImg:commonUrl+'image/yangjunjie-head.png',
			countryName:'美国',	
			countryFlag:commonUrl+'image/American.png',
			html:commonUrl+'page/yangjunjie.html'
		},{
			name:'王大仁',	
			id:'wangdaren',
			city:'newYork',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/wangdaren-big.png',
			desiginSmallimg:commonUrl+'image/wangdaren-small.png',		
			background:commonUrl+'image/wangdaren-bg.png',					
			headImg:commonUrl+'image/wangdaren-head.png',
			countryName:'美国',	
			countryFlag:commonUrl+'image/flag-American.png',
			html:commonUrl+'page/wangdaren.html'
		},{
			name:'张旸',	
			id:'zhangyang',
			city:'taiwan',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/zhangyang-big.png',
			desiginSmallimg:commonUrl+'image/zhangyang-small.png',		
			background:commonUrl+'image/zhangyang-bg.png',					
			headImg:commonUrl+'image/zhangyang-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zhangyang.html'
		},{
			name:'郭培',	
			id:'guopei',
			city:'Paris',			
			discribCity:'PARIS',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/guopei-big.png',
			desiginSmallimg:commonUrl+'image/guopei-small.png',		
			background:commonUrl+'image/guopei-bg.png',					
			headImg:commonUrl+'image/guopei-head.png',
			countryName:'法国',	
			countryFlag:commonUrl+'image/flag-France.png',
			html:commonUrl+'page/guopei.html'
		},{
			name:'Lucien-Wang',	
			id:'Lucien-Wang',
			city:'Paris',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/Lucien-Wang-big.png',
			desiginSmallimg:commonUrl+'image/Lucien-Wang-small.png',		
			background:commonUrl+'image/Lucien-Wang-bg.png',					
			headImg:commonUrl+'image/Lucien-Wang-head.png',
			countryName:'法国',	
			countryFlag:commonUrl+'image/flag-France.png',
			html:commonUrl+'page/Lucien-Wang.html'
		},{
			name:'fangfang',	
			id:'fangfang',
			city:'Milan',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/fangfang-big.png',
			desiginSmallimg:commonUrl+'image/fangfang-small.png',		
			background:commonUrl+'image/fangfang-bg.png',					
			headImg:commonUrl+'image/fangfang-head.png',
			countryName:'意大利',	
			countryFlag:commonUrl+'image/flag-Italy.png',
			html:commonUrl+'page/fangfang.html'
		},{
			name:'刘璐璐',	
			id:'liululu',
			city:'London',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/liululu-big.png',
			desiginSmallimg:commonUrl+'image/liululu-small.png',		
			background:commonUrl+'image/liululu-bg.png',					
			headImg:commonUrl+'image/liululu-head.png',
			countryName:'英国',	
			countryFlag:commonUrl+'image/flag-Britain.png',
			html:commonUrl+'page/liululu.html'
		},{
			name:'谢锋',	
			id:'xiefeng',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/xiefeng-big.png',
			desiginSmallimg:commonUrl+'image/xiefeng-small.png',		
			background:commonUrl+'image/xiefeng-bg.png',					
			headImg:commonUrl+'image/xiefeng-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/xiefeng.html'
		},{
			name:'祁刚',	
			id:'qigang',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/qigang-big.png',
			desiginSmallimg:commonUrl+'image/qigang-small.png',		
			background:commonUrl+'image/qigang-bg.png',					
			headImg:commonUrl+'image/qigang-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/qigang.html'
		},{
			name:'王玉涛',	
			id:'wangyutao',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/wangyutao-big.png',
			desiginSmallimg:commonUrl+'image/wangyutao-small.png',		
			background:commonUrl+'image/wangyutao-bg.png',					
			headImg:commonUrl+'image/wangyutao-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/wangyutao.html'
		},{
			name:'RanFan',	
			id:'RanFan',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/RanFan-big.png',
			desiginSmallimg:commonUrl+'image/RanFan-small.png',		
			background:commonUrl+'image/RanFan-bg.png',					
			headImg:commonUrl+'image/RanFan-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/RanFan.html'
		},{
			name:'姜悦音',	
			id:'jiangyueyin',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/jiangyueyin-big.png',
			desiginSmallimg:commonUrl+'image/jiangyueyin-small.png',		
			background:commonUrl+'image/jiangyueyin-bg.png',					
			headImg:commonUrl+'image/jiangyueyin-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/jiangyueyin.html'
		},{
			name:'魏腾飞',	
			id:'weipengfei',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/weipengfei-big.png',
			desiginSmallimg:commonUrl+'image/weipengfei-small.png',		
			background:commonUrl+'image/weipengfei-bg.png',					
			headImg:commonUrl+'image/weipengfei-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/weipengfei.html'
		},{
			name:'刘芳',	
			id:'liufang',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/liufang-big.png',
			desiginSmallimg:commonUrl+'image/liufang-small.png',		
			background:commonUrl+'image/liufang-bg.png',					
			headImg:commonUrl+'image/liufang-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/liufang.html'
		},{
			name:'秦旭',	
			id:'qinxu',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/qinxu-big.png',
			desiginSmallimg:commonUrl+'image/qinxu-small.png',		
			background:commonUrl+'image/qinxu-bg.png',					
			headImg:commonUrl+'image/qinxu-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/qinxu.html'
		},{
			name:'CJ姚',	
			id:'CJyao',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/CJyao-big.png',
			desiginSmallimg:commonUrl+'image/CJyao-small.png',		
			background:commonUrl+'image/CJyao-bg.png',					
			headImg:commonUrl+'image/CJyao-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/CJyao.html'
		},{
			name:'杨芳',	
			id:'yangfang',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/yangfang-big.png',
			desiginSmallimg:commonUrl+'image/yangfang-small.png',		
			background:commonUrl+'image/yangfang-big.png-bg.png',					
			headImg:commonUrl+'image/yangfang-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/yangfang.html'
		},{
			name:'王聪',	
			id:'wangcong',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/wangcong-big.png',
			desiginSmallimg:commonUrl+'image/wangcong-small.png',		
			background:commonUrl+'image/wangcong-big.png-bg.png',					
			headImg:commonUrl+'image/wangcong-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/wangcong.html'
		},{
			name:'邹游',	
			id:'zouyou',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/zouyou-big.png',
			desiginSmallimg:commonUrl+'image/zouyou-small.png',		
			background:commonUrl+'image/zouyou-big.png-bg.png',					
			headImg:commonUrl+'image/zouyou-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zouyou.html'
		},{
			name:'齐斌',	
			id:'qibin',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/qibin-big.png',
			desiginSmallimg:commonUrl+'image/qibin-small.png',		
			background:commonUrl+'image/qibin-big.png-bg.png',					
			headImg:commonUrl+'image/qibin-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/qibin.html'
		},{
			name:'匡峻',	
			id:'kuangjun',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/kuangjun-big.png',
			desiginSmallimg:commonUrl+'image/kuangjun-small.png',		
			background:commonUrl+'image/kuangjun-big.png-bg.png',					
			headImg:commonUrl+'image/kuangjun-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/kuangjun.html'
		},{
			name:'康悦',	
			id:'kangyue',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/kangyue-big.png',
			desiginSmallimg:commonUrl+'image/kangyue-small.png',		
			background:commonUrl+'image/kangyue-big.png-bg.png',					
			headImg:commonUrl+'image/kangyue-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/kangyue.html'
		},{
			name:'朱小杰',	
			id:'zhuxiaojie',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/zhuxiaojie-big.png',
			desiginSmallimg:commonUrl+'image/zhuxiaojie-small.png',		
			background:commonUrl+'image/zhuxiaojie-big.png-bg.png',					
			headImg:commonUrl+'image/zhuxiaojie-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zhuxiaojie.html'
		},{
			name:'赵伟伟',	
			id:'zhaoweiwei',
			city:'China',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/zhaoweiwei-big.png',
			desiginSmallimg:commonUrl+'image/zhaoweiwei-small.png',		
			background:commonUrl+'image/zhaoweiwei-big.png-big.png-bg.png',					
			headImg:commonUrl+'image/zhaoweiwei-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zhaoweiwei.html'
		},{
			name:'时尚合作',	
			id:'shishanghezuo',
			city:'shishanghezuo',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/zhaoweiwei-big.png',
			desiginSmallimg:commonUrl+'image/zhaoweiwei-small.png',		
			background:commonUrl+'image/zhaoweiwei-big.png-big.png-bg.png',					
			headImg:commonUrl+'image/shishanghezuo-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zhaoweiwei.html'
		},{
			name:'法新集团',	
			id:'faxinjituan',
			city:'shishanghezuo',			
			discribCity:'NEW YORK',
			discribTit:'Alexander Wang',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/zhaoweiwei-big.png',
			desiginSmallimg:commonUrl+'image/zhaoweiwei-small.png',		
			background:commonUrl+'image/zhaoweiwei-big.png-big.png-bg.png',					
			headImg:commonUrl+'image/faxinjituan-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zhaoweiwei.html'
		},]
