var commonUrl=location.href.split('page')[0]//.../src




function setSessionStorage(k,v,b){
	if(b){
		sessionStorage.setItem(k,JSON.stringify(v))
		return;
	}
	sessionStorage.setItem(k,v)
}
function getSessionStorage(k,b){
	let mid=sessionStorage.getItem(k);
	if(b&&mid){
		return JSON.parse(mid);
	}
	return mid;
}

//导航信息
var navInfo=[
{name:'首页'},
{name:'中国',active:false,type:'city',city:'China',countryFlag:commonUrl+'image/flag-China.png'},
{name:'巴黎',active:false,type:'city',city:'Paris',countryFlag:commonUrl+'image/flag-France.png'},
{name:'纽约',active:false,type:'city',city:'newYork',countryFlag:commonUrl+'image/flag-American.png'},
{name:'伦敦',active:false,type:'city',city:'London',countryFlag:commonUrl+'image/flag-Britain.png'},
{name:'米兰',active:false,type:'city',city:'Milan',countryFlag:commonUrl+'image/flag-Italy.png'},
{name:'台湾',active:false,type:'city',city:'taiwan',countryFlag:commonUrl+'image/flag-China.png'},
{name:'北欧',active:false,type:'city',city:'NorthernEurope',countryFlag:commonUrl+'image/flag-NorthernEurope.png'},
{name:'时尚合作',active:false,type:'city',city:'shishanghezuo',countryFlag:commonUrl+'image/flag-Fashion.png'},
];
// 设计师信息
var designerInfo=[{
			name:'Alexander King',
			showName:false,
			id:'king',
			city:'newYork',					
			active:false,					
			discribCity:'NEW YORK',
			discribTit:'ALEXANDER KING',
			discribBrand:['ALEXANDER KING CHEN','设计师陈科維ALEX的同名品牌'],
			meContent:['亚洲设计师，设计前卫、大胆，不按牌理出牌，独树一格，媒体新宠儿，也是国内手屈一指的黄金单身汉之一。经常受邀至纽约，上海举办服装秀，2017世界皮草协会，唯一赞助品牌盛名也是众多女星拥护者，范冰冰、蔡依林、萧亚轩、田馥甄、张韶涵、Ella等…','2009年在纽约自创同名品牌之后，因为家庭因素将其带回亚洲。主要销售区域为台湾。'],
			desiginBigimg:commonUrl+'image/king-big.jpg',
			desiginSmallimg:commonUrl+'image/king-small.jpg',		
			background:commonUrl+'image/king-bg.jpg',	
			headImg:commonUrl+'image/king-head.png',			
			countryName:'美国',	
			countryFlag:commonUrl+'image/flag-American.png',
			html:commonUrl+'page/king.html'
		},{
			name:'杨峻杰',	
			showName:false,
			id:'yangjunjie',
			city:'newYork',			
			active:false,					
			discribCity:'NEW YORK',
			discribTit:'杨峻杰',
			discribBrand:['清华大学美术学院服装设计系','安特卫普皇家艺术学院'],
			meContent:[' 曾在比利时设计师Raf Simons工作室以男装设计师的职务实习，目前在比利时品牌Walter Van Beirandonck担任印花设计兼男装设计助理职务。','于2017年在比利时安特卫普的男装品牌，致力于塑造东方审美情趣为主导内核，同西方后现代主义结合的千禧一代的年轻时装。年轻，无惧（young,bold,daring,smart)是品牌想要传递的形象。主要销售区域为中国。'],
			desiginBigimg:commonUrl+'image/yangjunjie-big.jpg',
			desiginSmallimg:commonUrl+'image/yangjunjie-small.jpg',		
			background:commonUrl+'image/yangjunjie-bg.jpg',	
			headImg:commonUrl+'image/yangjunjie-head.png',
			countryName:'美国',	
			countryFlag:commonUrl+'image/American.png',
			html:commonUrl+'page/yangjunjie.html'
		},{
			name:'Alexander Wang',	
			showName:false,
			id:'wangdaren',
			city:'newYork',			
			active:false,					
			discribCity:'NEW YORK',
			discribTit:'ALEXANDER WANG',
			discribBrand:['王大仁是华裔ABC','纽约最红最年轻的华裔设计师'],
			meContent:['1984年出生于美国旧金山，18岁时搬去纽约，并在纽约著名得时装设计学院Parsons攻读设计专业，Alexander二年级时就在Marc Jacobs品牌和《Vogue》杂志实习，多次获得CFDA等颁发的时装界大奖，他的设计堪称叫好又叫座，销售更是节节攀升。',' 在刚刚过去的2018纽约时装周，王大仁与哥本哈根皮草展开了合作。主要的销售区域在全球各地。'],
			desiginBigimg:commonUrl+'image/wangdaren-big.jpg',
			desiginSmallimg:commonUrl+'image/wangdaren-small.jpg',		
			background:commonUrl+'image/wangdaren-bg.jpg',					
			headImg:commonUrl+'image/wangdaren-head.png',
			countryName:'美国',	
			countryFlag:commonUrl+'image/flag-American.png',
			html:commonUrl+'page/wangdaren.html'
		},{
			name:'张旸',	
			showName:false,
			id:'zhangyang',
			city:'taiwan',			
			active:false,					
			discribCity:'TAIWAN',
			discribTit:'张旸',
			discribBrand:['中国台北定制设计师的代表','毕业于巴黎制衣公会'],
			meContent:['创立了自有品牌HOMME VAN LAB，系列作品多从历史、艺术和文化的角度重新阐述当代的社会样貌。',' 张旸擅长将艺术性的印花配合独有的版型来体现一个系列的故事性，他的表现手法使HOMME VAN LAB成为具有阅读性的时尚品牌。主要销售区域为台湾。'],
			desiginBigimg:commonUrl+'image/zhangyang-big.jpg',
			desiginSmallimg:commonUrl+'image/zhangyang-small.jpg',		
			background:commonUrl+'image/zhangyang-bg.jpg',					
			headImg:commonUrl+'image/zhangyang-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zhangyang.html'
		},{
			name:'郭培',	
			showName:false,
			id:'guopei',
			city:'Paris',			
			active:false,					
			discribCity:'PARIS',
			discribTit:'郭培',
			discribBrand:['中国首位被世界认可的高级服装设计师',''],
			meContent:['作为第一代中国服装设计师，她自1986年以来在专业领域不断探索，成为北京天马服装公司的首席设计师，之后在 1997 年创立北京玫瑰坊时装订制有限公司，开创了年来广博赞誉的高级订制，都是郭培不断地挑战自我、追求最完美设计的过程。作为高级订制在中国最早的推动者之一，郭培的玫瑰坊无疑代表着中国高级订制的最高水准。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/guopei-big.jpg',
			desiginSmallimg:commonUrl+'image/guopei-small.jpg',		
			background:commonUrl+'image/guopei-bg.jpg',					
			headImg:commonUrl+'image/guopei-head.png',
			countryName:'法国',	
			countryFlag:commonUrl+'image/flag-France.png',
			html:commonUrl+'page/guopei.html'
		},{
			name:'Lucien-Wang',	
			showName:false,
			id:'lucien-wang',
			city:'Paris',			
			active:false,					
			discribCity:'PARIS',
			discribTit:'LUCIEN WANG',
			discribBrand:['毕业于法国巴黎studio berco服装设计学院',''],
			meContent:['  2008年，在世界时装之都巴黎创立一自己名字命名的品牌lucien wang。2012年lucien wang品牌在北京设计了工作室，产品范围涵盖了高级女装成衣、手袋、配饰、鞋履等。2013年11约正式推出高级成衣2014春夏系列，2016年12月以发布8个完整女装成衣系列，2014年，lucien荣列为纪念中法建交五十年而全球播映的法语系列人物短片《50年50人》名单。主要销售区域为北京。'],
			desiginBigimg:commonUrl+'image/lucien-wang-big.jpg',
			desiginSmallimg:commonUrl+'image/lucien-wang-small.jpg',		
			background:commonUrl+'image/lucien-wang-bg.jpg',					
			headImg:commonUrl+'image/lucien-wang-head.png',
			countryName:'法国',	
			countryFlag:commonUrl+'image/flag-France.png',
			html:commonUrl+'page/lucien-wang.html'
		},{
			name:'FangFang',	
			showName:false,
			id:'fangfang',
			city:'Milan',			
			active:false,					
			discribCity:'MILAN',
			discribTit:'FANGFANG',
			discribBrand:['伦敦时装学院男装设计研究生专业,品牌创始人',''],
			meContent:['2015 年CONSISTENCE 创建于英国伦敦。2016年开始获得ukft英国时装与面料协会的奖金参加巴黎时装周展会。2017年获得Giorgio Armani钦点，在众多设计师中脱颖而出，受邀赴米兰时装周官方日程走秀，由阿玛尼先生和意大利时装协会全程赞助。国际知名裘皮供应商及皮草工艺创意研究所哥本哈根⽪草的对品牌赞誉有嘉，为品牌赞助所有皮草原料与技术支持。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/fangfang-big.jpg',
			desiginSmallimg:commonUrl+'image/fangfang-small.jpg',		
			background:commonUrl+'image/fangfang-bg.jpg',					
			headImg:commonUrl+'image/fangfang-head.png',
			countryName:'意大利',	
			countryFlag:commonUrl+'image/flag-Italy.png',
			html:commonUrl+'page/fangfang.html'
		},{
			name:'刘璐璐',	
			showName:false,
			id:'liululu',
			city:'London',			
			active:false,					
			discribCity:'LONDON',
			discribTit:'刘璐璐',
			discribBrand:['伦敦时装学院时装设计','致力于自己的商标LIU LULU'],
			meContent:[' LULU LIU是一个大胆而自信的品牌，让人们能够以原始而独特的方式展现出品牌的风格。该品牌将高端时尚的奢华和富裕与灵巧和品质相结合，开创了前沿服装，不仅显示了停顿和独特，也保持了耐用性、女性气质及优雅感。品牌关键的签名样式采用了大尺寸的衣褶，混合了皮草，长层，明亮的针织和鲜艳的色彩。主要销售区域为中国、英国。',''],
			desiginBigimg:commonUrl+'image/liululu-big.jpg',
			desiginSmallimg:commonUrl+'image/liululu-small.jpg',		
			background:commonUrl+'image/liululu-bg.jpg',					
			headImg:commonUrl+'image/liululu-head.png',
			countryName:'英国',	
			countryFlag:commonUrl+'image/flag-Britain.png',
			html:commonUrl+'page/liululu.html'
		},{
			name:'谢锋',	
			showName:false,
			id:'xiefeng',
			city:'China',			
			active:false,					
			discribCity:'CHINA',
			discribTit:'谢锋',
			discribBrand:['第一位被巴黎时装工会邀请的中国设计师',''],
			meContent:[' 北京吉芬时装设计股份有限公司艺术总监、董事长，中国时尚的开拓者. 1999年，创立设计师品牌JEFEN（吉芬）。','  2006年10月1日，个人所创立JEFEN品牌被选入巴黎时装周，于巴黎卢浮宫举办成衣发布会，成为中国在巴黎时装周发布的第一人。主要的销售区域为中国国内。'],
			desiginBigimg:commonUrl+'image/xiefeng-big.jpg',
			desiginSmallimg:commonUrl+'image/xiefeng-small.jpg',		
			background:commonUrl+'image/xiefeng-bg.jpg',					
			headImg:commonUrl+'image/xiefeng-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/xiefeng.html'
		},{
			name:'祁刚',	
			showName:false,
			id:'qigang',
			city:'China',			
			active:false,					
			discribCity:'CHINA',
			discribTit:'祁刚',
			discribBrand:['中国时装设计最高奖“金顶奖”设计师',''],
			meContent:['中国十大服装设计师、曾获上海国际时装节“大师”勋章、中国服装设计师协会主任委员、流行趋势研究员。',' SEC品牌艺术&设计总监，因长期为一线艺人如范冰冰、高圆圆、王冠等明星、名流定制高级时装，成为明星、名流最追捧的设计师。主要的销售区域为中国国内。'],
			desiginBigimg:commonUrl+'image/qigang-big.jpg',
			desiginSmallimg:commonUrl+'image/qigang-small.jpg',		
			background:commonUrl+'image/qigang-bg.jpg',					
			headImg:commonUrl+'image/qigang-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/qigang.html'
		},{
			name:'王玉涛',	
			showName:false,
			id:'wangyutao',
			city:'China',			
			active:false,					
			discribCity:'CHINA',
			discribTit:'王玉涛',
			discribBrand:['亚洲知名服装设计师','毕业于天津工艺美术学院'],
			meContent:['2005年创建Beautyberry品牌，2015年创建子品牌B+by Beautyberry并担任设计总监。对于生活在东方的他来说，他认为中国设计风格并不仅是简单在作品中添加一些中国元素。相比于作品表现形式，他更倾向于追求精神上的相似之处。在他看来，东方文化强调慢节奏的步伐和享受生活的乐趣。他尝试将这种随性的感觉融入作品当中，展现他所认为的“另一种中国风”主要的销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/wangyutao-big.jpg',
			desiginSmallimg:commonUrl+'image/wangyutao-small.jpg',		
			background:commonUrl+'image/wangyutao-bg.jpg',					
			headImg:commonUrl+'image/wangyutao-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/wangyutao.html'
		},{
			name:'RanFan',	
			showName:false,
			id:'fanran',
			city:'China',			
			active:false,					
			discribCity:'CHINA',
			discribTit:'范然',
			discribBrand:['范然创立个人品牌RanFan','中国服装协会最佳创意设计师'],
			meContent:['自幼立志成为时装设计师的范然早年求学于英国中央圣马丁艺术与设计学院，毕业作品荣获学院杰出设计奖。2009年回国后成立工作室，担任北服莱佛士国际学院服装设计讲师。','以建筑为灵感，精湛的裁剪，张弛有力的线条是Ran Fan的标签。Ran Fan 专为摩登、优雅、追求完美生活品质的女性而设计。范然的作品受到众多明星的热爱及追捧，并长期深得媒体关注。主要销售区域为中国。'],
			desiginBigimg:commonUrl+'image/fanran-big.jpg',
			desiginSmallimg:commonUrl+'image/fanran-small.jpg',		
			background:commonUrl+'image/fanran-bg.jpg',					
			headImg:commonUrl+'image/fanran-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/fanran.html'
		},{
			name:'姜悦音',	
			showName:false,
			id:'jiangyueyin',
			city:'China',			
			active:false,					
			discribCity:'CHINA',
			discribTit:'姜悦音',
			discribBrand:['设计师、明星御用造型师','平面设计师、时尚博主'],
			meContent:[' POLLYANNA KEONG品牌是由澳门籍设计师姜悦音Pollyanna创立，品牌有其独有设计语言，用考究的选料、复古的剪裁和灵动的图案描绘出少女们的梦想。','穿着POLLYANNA KEONG的“PK GIRLS & BOYS”是那些时髦前卫的都市男孩女孩，怀揣一颗不老的少女心，穿出自己古灵精怪俏皮天真的搭配风格。主要的收受区域为中国。'],
			desiginBigimg:commonUrl+'image/jiangyueyin-big.jpg',
			desiginSmallimg:commonUrl+'image/jiangyueyin-small.jpg',		
			background:commonUrl+'image/jiangyueyin-bg.jpg',					
			headImg:commonUrl+'image/jiangyueyin-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/jiangyueyin.html'
		},{
			name:'魏腾飞',	
			showName:false,
			id:'weitengfei',
			city:'China',			
			active:false,					
			discribCity:'CHINA',
			discribTit:'魏腾飞',
			discribBrand:['2009年入中央美术学院设计学院时装设计系',''],
			meContent:['2009.11年创立自己的品牌JAMY WEE。12年创立时装公司北京杰米魏衣服装有限公司。2015年与哥本哈根合作皮草系列，款式为挪威银狐与哥本哈根水貂的完美结合。主要的销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/weitengfei-big.jpg',
			desiginSmallimg:commonUrl+'image/weitengfei-small.jpg',		
			background:commonUrl+'image/weitengfei-bg.jpg',					
			headImg:commonUrl+'image/weitengfei-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/weitengfei.html'
		},{
			name:'刘芳',	
			showName:false,
			id:'liufang',
			city:'China',			
			active:false,
			index:7,				
			discribCity:'CHINA',
			discribTit:'刘芳',
			discribBrand:['中国服装设计师协会艺术委员会委员，软黄金的雕塑师',''],
			meContent:['       北京简智方达服装服饰有限公司设计总监兼董事长，时尚羊绒品牌“SS”的设计总监，并为欧洲多个高级时装屋提供羊绒针织成衣设计；曾任帕罗设计总监兼CEO。设计风格专长于用羊绒针织工艺手法写意优雅、唯美、先锋感的设计师。曾多次荣获中国国际时装周“最佳女装设计奖”、“中国十佳设计师”，多次荣获中国服装协会CCDC中国当代设计邀请赛“最佳针织创新奖”等。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/liufang-big.jpg',
			desiginSmallimg:commonUrl+'image/liufang-small.jpg',		
			background:commonUrl+'image/liufang-bg.jpg',					
			headImg:commonUrl+'image/liufang-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/liufang.html'
		},{
			name:'秦旭',	
			showName:false,
			id:'qinxu',
			city:'China',			
			active:false,	
			index:8,				
			discribCity:'CHINA',
			discribTit:'秦旭',
			discribBrand:['莱弗士国际设计学院','MOODBOX设计总监&创始人'],
			meContent:['       上海秦旭服饰有限公司CEO，中国原创服装设计师、造型师、高级服装定制师，上海服装设计师协会会员，秦旭强调站在变化的视角来观察、体验生活，借以服装来表现现实世界的事物与情感，着重研究满足女性瞬间心情变化的着装需求服饰；从而形成了MOODBOX“一衣多穿”的液态设计理念。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/qinxu-big.jpg',
			desiginSmallimg:commonUrl+'image/qinxu-small.jpg',		
			background:commonUrl+'image/qinxu-bg.jpg',					
			headImg:commonUrl+'image/qinxu-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/qinxu.html'
		},{
			name:'CJ姚',	
			showName:false,
			id:'CJyao',
			city:'China',			
			active:false,
			index:9,					
			discribCity:'CHINA',
			discribTit:'CJ姚',
			discribBrand:['毕业于伦敦中央圣马丁设计学院2012年创立品牌"C.J. YAO"',''],
			meContent:['曾在2006年荣获新加坡时装周上的“亚洲青年设计师比赛（Asian Young Fashion Designer Contest）”的亚军头衔；之后在同一年里，获得了由“CHINA FASHION FOUNDATION”筹办的 “Young Fashion Designers Overseas Internship Program”冠军。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/CJyao-big.jpg',
			desiginSmallimg:commonUrl+'image/CJyao-small.jpg',		
			background:commonUrl+'image/CJyao-bg.jpg',					
			headImg:commonUrl+'image/CJyao-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/CJyao.html'
		},{
			name:'杨芳',	
			showName:false,
			id:'yangfang',
			city:'China',			
			active:false,
			index:10,					
			discribCity:'CHINA',
			discribTit:'杨芳',
			discribBrand:['中国时尚界领军设计师之一','巴黎ESMOD学习时装设计'],
			meContent:['作品以其柔美的线条、精致的剪裁和标志性的折纸元素受到时尚界的认可。品牌精益求精，甄选来自全世界各地顶级面料。该品牌由成衣线（by FANG）与定制线（Atelier by FANG）构成，客户可以预约前往上海工作室与设计师会面，享受独一无二的高级定制体验。从纽约到巴黎，从上海到东京，许多高端百货店都能看到品牌的身影。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/yangfang-big.jpg',
			desiginSmallimg:commonUrl+'image/yangfang-small.jpg',		
			background:commonUrl+'image/yangfang-bg.jpg',					
			headImg:commonUrl+'image/yangfang-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/yangfang.html'
		},{
			name:'王聪',	
			showName:false,
			id:'wangcong',
			city:'China',			
			active:false,
			index:11,					
			discribCity:'CHINA',
			discribTit:'王聪',
			discribBrand:['北京服装学院服装艺术设计专业','2014年冬创立了这服装配饰品牌'],
			meContent:['曾在外企工作4年，期间接触了大量冬季材质，渐渐的对各种皮草、真皮有了很熟悉的了解。时间的沉淀让她彻底爱上了这些柔软的质地。她敏锐地収现这一市场的相对空缺，喜欢求变，永远对新鲜的事物感兴趣，也总能第一时间捕捉到新鲜的信息，所以在企划事业中一直想找市场的空缺，不喜欢复制别人走过的路径。主要销售区域为中国。',' '],
			desiginBigimg:commonUrl+'image/wangcong-big.jpg',
			desiginSmallimg:commonUrl+'image/wangcong-small.jpg',		
			background:commonUrl+'image/wangcong-bg.jpg',					
			headImg:commonUrl+'image/wangcong-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/wangcong.html'
		},{
			name:'邹游',	
			showName:false,
			id:'zouyou',
			city:'China',			
			active:false,	
			index:12,				
			discribCity:'CHINA',
			discribTit:'邹游',
			discribBrand:['中央美术院博士','北京服装学院副教授'],
			meContent:['长期致力于时装设计与设计管理的研究，曾多次参与大型艺术活动的造型及服装产品开发设计项目。近年来，连续在“中国国际时装周”推出个人作品系列发布会，曾多次获得国家级奖项。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/zouyou-big.jpg',
			desiginSmallimg:commonUrl+'image/zouyou-small.jpg',		
			background:commonUrl+'image/zouyou-bg.jpg',					
			headImg:commonUrl+'image/zouyou-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zouyou.html'
		},{
			name:'齐斌',	
			showName:false,
			id:'qibin',
			city:'China',			
			active:false,	
			index:13,				
			discribCity:'CHINA',
			discribTit:'齐斌',
			discribBrand:['北京服装学院本科；欧洲设计学院IED米兰分院硕士研究生',''],
			meContent:['        第七届CCTV电视全国服装设计大赛金奖以及最佳创意奖，同年作品参加香港皮草展；第三届中国国际女装设计大赛金奖并全额奖学金赴意大利留学；现供事于米兰国际面料展流行色协会主席旗下设计师。2012年于米兰注册高端女装品牌ALLAN 28，是融自然智慧于创作灵感的经典之作。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/qibin-big.jpg',
			desiginSmallimg:commonUrl+'image/qibin-small.jpg',		
			background:commonUrl+'image/qibin-bg.jpg',					
			headImg:commonUrl+'image/qibin-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/qibin.html'
		},{
			name:'匡峻',	
			showName:false,
			id:'kuangjun',
			city:'China',			
			active:false,	
			index:14,				
			discribCity:'CHINA',
			discribTit:'匡峻',
			discribBrand:['中央美术学院雕塑系','以职业艺术家的身份生活于北京'],
			meContent:['        作品源于2013年为武汉美术馆创作的 一系列作品“唯心之物”，我将冬瓜，黄瓜，苦瓜等日常物，从饱满到干枯形态并列起来，生成一个全新的物体。这次，我想用皮草的特性质感和金属结合，再创作一系列和花有关的雕塑，有绽放，有枯萎。借此来表达东方审美中对生命的独特理解。2016年，与哥本哈根皮草首次合作，皮草雕塑艺术品在丹麦使馆开放日上展出。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/kuangjun-big.jpg',
			desiginSmallimg:commonUrl+'image/kuangjun-small.jpg',		
			background:commonUrl+'image/kuangjun-bg.jpg',					
			headImg:commonUrl+'image/kuangjun-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/kuangjun.html'
		},{
			name:'康悦',	
			showName:false,
			id:'kangyue',
			city:'China',			
			active:false,		
			index:15,			
			discribCity:'CHINA',
			discribTit:'康悦',
			discribBrand:['现工作于中国艺术研究院','毕业于西安美术学院雕塑系'],
			meContent:['       2015年参展：新态·2015太原国际雕塑双年展，太原美术馆。第七届中韩现代雕塑交流展，首尔Arts Center。物语——ZERO 第二届当代女性雕塑展，北京798零艺术中心 。2014年参展：“蒲公英”哥本哈根皮草中国艺术展，北京王府半岛酒店 。第三届造型艺术新人展并获得新人佳作提名奖，中国美术馆 中央美术学院第六届“为坐而设计”大奖赛并获得铜奖，中央美院美术馆。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/kangyue-big.jpg',
			desiginSmallimg:commonUrl+'image/kangyue-small.jpg',		
			background:commonUrl+'image/kangyue-bg.jpg',					
			headImg:commonUrl+'image/kangyue-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/kangyue.html'
		},{
			name:'朱小杰',	
			showName:false,
			id:'zhuxiaojie',
			city:'China',			
			active:false,	
			index:16,				
			discribCity:'CHINA',
			discribTit:'朱小杰',
			discribBrand:['中国著名家具设计师','中国家具设计专业委员会副主任'],
			meContent:['        当过石匠，木匠，钳工，会计，最后回到受益人的角色。1978年留学澳大利亚悉尼，并从事室内设计。1994年回国组建澳珀家具公司。中国美院客座教授，策展人，温州家具学院院长，澳珀家具艺术总监及设计师，小杰工作室的头。主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/zhuxiaojie-big.jpg',
			desiginSmallimg:commonUrl+'image/zhuxiaojie-small.jpg',		
			background:commonUrl+'image/zhuxiaojie-bg.jpg',					
			headImg:commonUrl+'image/zhuxiaojie-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zhuxiaojie.html'
		},{
			name:'赵伟伟',	
			showName:false,
			id:'zhaoweiwei',
			city:'China',			
			active:false,	
			index:17,				
			discribCity:'CHINA',
			discribTit:'赵伟伟',
			discribBrand:['中央美术学院时装设计专业','L&XF杯全国时装画艺术大赛金奖'],
			meContent:['曾获得哥本哈根首届皮草配饰创意大赛一等奖。作品多次参加时装艺术国际展以及国内相关专业展览，并参与上海世博会中国馆工作服设计、APEC亚太会议服饰设计、中国会馆工作服设计等设计项目。设计方向涉及时装、皮草皮具、平面视觉、珠宝配饰等。连续四届受邀参加时装艺术国际展，参加北京设计周 CHIC YOUNG BLOOD设计师联展，主要销售区域为中国。',''],
			desiginBigimg:commonUrl+'image/zhaoweiwei-big.jpg',
			desiginSmallimg:commonUrl+'image/zhaoweiwei-small.jpg',		
			background:commonUrl+'image/zhaoweiwei-bg.jpg',					
			headImg:commonUrl+'image/zhaoweiwei-head.png',
			countryName:'中国',	
			countryFlag:commonUrl+'image/flag-China.png',
			html:commonUrl+'page/zhaoweiwei.html'
		},{
			name:'乔根·西蒙森',	
			showName:false,
			id:'jorgesimonsen',
			city:'NorthernEurope',			
			active:false,					
			discribCity:'DENMARK',
			discribTit:'乔根·西蒙森',
			discribBrand:['法国巴黎高级时装工会学校','时尚界最有影响力的独立设计师'],
			meContent:['九十年代后期他被米兰时尚帝国范思哲（Versace）任命为首席设计师，之后又被罗马殿堂级高级时装品牌华伦天奴（Valentino）聘用为数季系列产品的首席设计师。除了和众多国际大牌的合作，乔根·西蒙森还担任过电影的时尚顾问，为参加戛纳电影节的导演定制礼服, 并多次推出了个人品牌的高定系列，其服装设计风格和工艺水平深受各界名流的青睐。',''],
			desiginBigimg:commonUrl+'image/jorgesimonsen-big.jpg',
			desiginSmallimg:commonUrl+'image/jorgesimonsen-small.jpg',		
			background:commonUrl+'image/jorgesimonsen-bg.jpg',					
			headImg:commonUrl+'image/jorgesimonsen-head.png',
			countryName:'北欧',	
			countryFlag:commonUrl+'image/flag-NorthernEurope.png',
			html:commonUrl+'page/jorgesimonsen.html'
		},{
			name:'时尚集团',	
			showName:false,
			id:'shishangjituan',
			city:'shishanghezuo',			
			active:false,					
			discribCity:'FASHION COOPERATION',
			discribTit:'时尚集团',
			discribBrand:['中国高档生活消费类期刊的始创','者，具有国际影响力的传媒集团'],
			meContent:['时尚集团诞生于1993年，凭借“国际视野、本土意识”的理念，时尚集团率先与世界一流出版集团强强联手，采取版权合作的形式，从一本杂志开始，至今已发展成为拥有17本高档期刊，业务涵盖期刊编辑、图书策划、网络传媒、广告、印刷、发行、数字出版、电视制作等多项领域的跨媒体多平台的传媒集团，并在上海和广州设立广告、发行分公司、办事处。',''],
			desiginBigimg:commonUrl+'image/shishangjituan-big.jpg',
			desiginSmallimg:commonUrl+'image/shishangjituan-small.jpg',		
			background:commonUrl+'image/shishangjituan-bg.jpg',					
			headImg:commonUrl+'image/shishangjituan-head.png',
			countryName:'时尚合作',	
			countryFlag:commonUrl+'image/flag-Fashion.png',
			html:commonUrl+'page/shishangjituan.html'
		},{
			name:'法新集团',	
			showName:false,
			id:'faxinjituan',
			city:'shishanghezuo',			
			active:false,					
			discribCity:'FASHION COOPERATION',
			discribTit:'CCDC',
			discribBrand:['让一切源于生活的创意融入最平','实的生活中'],
			meContent:['糅合时尚，艺术，传媒与制造等多元领域，全方位诠释创意，多角度引进文化。汇聚海内外设计师，当代艺术家及各领域意见领袖，消融行业壁垒，激发创意源泉，让思想与行动“无界”，让创意与创意“联盟”。“ccdc中国时装设计创意邀请赛”－－搭筑国内设计通向国际舞台的龙门天梯。“china in paris中国创意在巴黎”－－架构中国创意与国际对话的抵住桥梁。',''],
			desiginBigimg:commonUrl+'image/faxinjituan-big.jpg',
			desiginSmallimg:commonUrl+'image/faxinjituan-small.jpg',		
			background:commonUrl+'image/faxinjituan-bg.jpg',					
			headImg:commonUrl+'image/faxinjituan-head.png',
			countryName:'时尚合作',	
			countryFlag:commonUrl+'image/flag-Fashion.png',
			html:commonUrl+'page/faxinjituan.html'
		},]
